-- [V] Sequence : 순차번호 생성기. 대부분 인위적인 PK사용용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 --1부터 시작(기본값)
    INCREMENT BY 1 --1씩 증가(기본값)
    MAXVALUE 9999 --최대값
    MINVALUE 1 --최소값
    NOCYCLE -- CYCLE : 순차번호 9999->1
    NOCACHE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; -- 다음 순차번호 값
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; --현재 시퀀스 값

DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(250),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 99999
    NOCACHE NOCYCLE;
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES(FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999', '서울');
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
    VALUES(FRIEND_SEQ.NEXTVAL, '유길동', NULL, '서울');
SELECT * FROM FRIEND;
DELETE FROM FRIEND WHERE TEL IS NULL;

-- ※연습문제
DROP TABLE MEMBER_LEVEL;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(1) PRIMARY KEY,
    LEVELNAME VARCHAR2(10) NOT NULL
);

DROP SEQUENCE MEMBER_MNO_SQ;
CREATE SEQUENCE MEMBER_MNO_SQ
    START WITH 1
    INCREMENT BY 1
    NOCYCLE 
    NOCACHE;

DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    mNO NUMBER PRIMARY KEY,
    mNAME VARCHAR2(10) NOT NULL,
    mPW VARCHAR2(8),
    mEMAIL VARCHAR2(20) UNIQUE,
    mPOINT NUMBER(5) CHECK(mPOINT>=0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(1) REFERENCES MEMBER_LEVEL(LEVELNO)
);
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (-1, 'black');
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME) VALUES (2, '골드');
INSERT INTO MEMBER VALUES( MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, TO_DATE('24/09/26', 'RR/MM/DD'), 0);
INSERT INTO MEMBER VALUES( MEMBER_MNO_SQ.NEXTVAL, '홍길동', 'bb', 'sin@sin.com', 1000, TO_DATE('22/04/01', 'RR/MM/DD'), 1);
SELECT * FROM MEMBER

-- INSERT INTO MEMER_LEVEL~
--INSERT INTO MENBER~
-- 연습문제와 같이 출력되도록 SELECT (EQUI JOIN)